name: WIP
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        with:
          # Set action to failed when wip.
          setFailed: false
          wip_description: 'work in progress (please do not merge)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}