name: WIP
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          description: 'work in progress (Do not merge)'